[workspace]

members = [
    "toy_star",
    "speed_up",
    "sphfunctions",
    "tree_algorithm",
    "find_neighbors",
    "structures",
    "accretion_disk",
    "sedov_blast_wave",
    "kelvin_helmholtz",
]
